
export const SHOW_LOGIN_DIALOG = 'SHOW_LOGIN_DIALOG';
export const HIDE_LOGIN_DIALOG = 'HIDE_LOGIN_DIALOG';
export const SET_REQUESTED_URL  =  'SET_REQUESTED_URL';
export const SHOW_LOGIN_DIALOG_SET_REQUESTED_URL  = 'SHOW_LOGIN_DIALOG_SET_REQUESTED_URL';
