
export const CHECK_USER_PROFILE_NAME_ATTEMPT = 'CHECK_USER_PROFILE_NAME_ATTEMPT';
export const CHECK_USER_PROFILE_NAME_SUCCESS = 'CHECK_USER_PROFILE_NAME_SUCCESS';
export const CHECK_USER_PROFILE_NAME_FAILURE = 'CHECK_USER_PROFILE_NAME_FAILURE';

export const RESET_USER_PROFILE_NAME_VALID = 'RESET_USER_PROFILE_NAME_VALID';

export const SET_SELECTED_PROFILE_ID = 'SET_SELECTED_PROFILE_ID';


export const GET_USER_PROFILE_ATTEMPT = 'GET_USER_PROFILE_ATTEMPT';
export const GET_USER_PROFILE_FAILURE = 'GET_USER_PROFILE_FAILURE';
export const GET_USER_PROFILE_SUCCESS = 'GET_USER_PROFILE_SUCCESS';

export const EDIT_USER_PROFILE_ATTEMPT = 'EDIT_USER_PROFILE_ATTEMPT';
export const EDIT_USER_PROFILE_SUCCESS = 'EDIT_USER_PROFILE_SUCCESS';
export const EDIT_USER_PROFILE_FAILURE = 'EDIT_USER_PROFILE_FAILURE';

export const REGISTER_USER_FAILURE = 'REGISTER_USER_FAILURE';
export const REGISTER_USER_ATTEMPT = 'REGISTER_USER_ATTEMPT';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';